Repository jupyterlab/jupyterlab-plugin-playground, pull requests merged in 2022-03, with the labels that each got.

#28 Transpile (optional) TypeScript, support imports (package and relative) and schema
  .eslintrc.js
  MANIFEST.in
  README.md
  RELEASE.md
  binder/overrides.json
  binder/postBuild
  package.json
  schema/plugin.json
  scripts/modules.py
  scripts/test.js
  scripts/widget.js
  src/dialogs.tsx
  src/errors.tsx
  src/index.ts
  src/loader.ts
  src/modules.ts
  src/raw-loader.d.ts
  src/requirejs.ts
  src/resolver.ts
  src/transpiler.ts
  src/types.ts
  webpack.config.js
  yarn.lock
Labels: enhancement

#35 Automated Changelog Entry for 0.4.0 on master
  CHANGELOG.md
Labels: documentation

#38 Rename default branch to `main`
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  README.md
Labels: maintenance
